### ISSUE TITLE
internationalization

### ISSUE THREAD

**Issue by raffaeleguidi** [timulto/timulto#1]
First thing should be the login form, which is currently the template one, only in english

**Comment by Licas** [comment]
Issue in progress. Following are reported some sha related to this issue, because I forgot to mention issue# in commit comment: 
- fe05ceffe15f60b9ae75d5c678f9321bf10f871a
- cf6e029bd4f5d3321b495942e19b026e33430aec

**Comment by Licas** [comment]
Added package and basic mechanism for internationalization. Some keys added to en and it.

**Comment by Licas** [comment]
in progress review of templates/pages wording.

**Comment by raffaeleguidi** [comment]
should be ok for now
