### ISSUE TITLE
push notifications

### ISSUE THREAD

**Issue by raffaeleguidi** [timulto/timulto#2]

**Comment by raffaeleguidi** [comment]
approval/reject of "fines" should be notified via push events

**Comment by Licas** [comment]
I'm planning to create a page "notifications" to show user's approved fine

**Comment by raffaeleguidi** [comment]
added cordova PushPlugin and client/push.js with some sample code and references to get started on the App's side @Licas

**Comment by raffaeleguidi** [comment]
done with notification of new fines to approve
