### ISSUE TITLE
Add "Share" buttons for Twitter/Facebook/Google+ on single fines and pages

### ISSUE THREAD

**Issue by Licas** [timulto/timulto#66]

**Comment by raffaeleguidi** [comment]
giving a try to https://atmospherejs.com/joshowens/shareit, beginning from the web site

**Comment by raffaeleguidi** [comment]
didn't like it. Tried socialite.js as well and didn't like it as well

**Comment by raffaeleguidi** [comment]
added likes and share for home page (web) and share for detail

**Comment by raffaeleguidi** [comment]
added fb and twitter likes to web site

**Comment by raffaeleguidi** [comment]
See The Spiderable Package for SEO FB optimization

**Comment by raffaeleguidi** [comment]
Add blaze-meta to handle facebook meta tags

**Comment by raffaeleguidi** [comment]
done using native apis
